rm logs/IW/ZDT1/*.csv
rm logs/IW/ZDT1/IGD/*.csv
rm logs/IW/ZDT2/*.csv
rm logs/IW/ZDT2/IGD/*.csv
rm logs/IW/ZDT3/*.csv
rm logs/IW/ZDT3/IGD/*.csv
rm logs/IW/ZDT4/*.csv
rm logs/IW/ZDT4/IGD/*.csv
rm logs/IW/ZDT6/*.csv
rm logs/IW/ZDT6/IGD/*.csv

rm logs/SP/ZDT1/*.csv
rm logs/SP/ZDT1/IGD/*.csv
rm logs/SP/ZDT2/*.csv
rm logs/SP/ZDT2/IGD/*.csv
rm logs/SP/ZDT3/*.csv
rm logs/SP/ZDT3/IGD/*.csv
rm logs/SP/ZDT4/*.csv
rm logs/SP/ZDT4/IGD/*.csv
rm logs/SP/ZDT6/*.csv
rm logs/SP/ZDT6/IGD/*.csv
